3-10:3-10-main.o 3-10-fun_sum.o 3-10-fun_avg.o
	gcc 3-10-main.o 3-10-fun_sum.o 3-10-fun_avg.o -o 3-10
3-10.main.o: 3-10-main.c chengji.h
	gcc 3-10-main.c -c
3-10-fun_avg.o: 3-10-fun_avg.c
	gcc 3-10-fun_avg.c -c